### ISSUE TITLE
Review Pages

### ISSUE THREAD

**Issue by nicholas-logan** [nicholas-logan/vigilant-waddle#2]
Take a look at each page to make sure nothing was missed.

**Comment by james-brattin** [comment]
Only thing I found was a missing favicon. I created a new branch where I added one. It's your project so feel free to change it. I made mine using this: https://formito.com/tools/favicon. I'll create a pull request with those changes.

**Comment by nicholas-logan** [comment]
Okay, I will take a look.

**Comment by nicholas-logan** [comment]
Review complete, looks good!
